sgAMIMOTO11AutogenByAWSMP do
  Type "AWS::EC2::SecurityGroup"
  Properties do
    GroupDescription "This security group was generated by AWS Marketplace and is based on recommended settings for AMIMOTO version 11 provided by DigitalCube Co Ltd"
    VpcId do
      Ref "AmimotoVPC"
    end
    SecurityGroupIngress [
      _{
        IpProtocol "tcp"
        FromPort 22
        ToPort 22
        CidrIp "0.0.0.0/0"
      },
      _{
        IpProtocol "tcp"
        FromPort 80
        ToPort 80
        CidrIp "0.0.0.0/0"
      }
    ]
  end
end
sgAMIMOTO11AutogenByAWSMPNFS do
  Type "AWS::EC2::SecurityGroup"
  Properties do
    GroupDescription "This security group was generated by AWS Marketplace and is based on recommended settings for AMIMOTO version 11 provided by DigitalCube Co Ltd"
    VpcId do
      Ref "AmimotoVPC"
    end
    SecurityGroupIngress [
      _{
        IpProtocol "tcp"
        FromPort 22
        ToPort 22
        CidrIp "0.0.0.0/0"
      },
      _{
        IpProtocol "tcp"
        FromPort 80
        ToPort 80
        CidrIp "0.0.0.0/0"
      },
      _{
        IpProtocol "tcp"
        FromPort 0
        ToPort 65535
        SourceSecurityGroupId do
          Ref "sgAMIMOTO11AutogenByAWSMP"
        end
      },
      _{
        IpProtocol "udp"
        FromPort 0
        ToPort 65535
        SourceSecurityGroupId do
          Ref "sgAMIMOTO11AutogenByAWSMP"
        end
      }
    ]
  end
end
sgAMIMOTO11AutogenByAWSMPforRDB do
  Type "AWS::EC2::SecurityGroup"
  Properties do
    GroupDescription "This security group was generated by AWS Marketplace and is based on recommended settings for AMIMOTO JINKEI version 11 provided by DigitalCube Co Ltd"
    VpcId do
      Ref "AmimotoVPC"
    end
    SecurityGroupIngress [
      _{
        IpProtocol "tcp"
        FromPort 3306
        ToPort 3306
        SourceSecurityGroupId do
          Ref "sgAMIMOTO11AutogenByAWSMP"
        end
      },
      _{
        IpProtocol "tcp"
        FromPort 3306
        ToPort 3306
        SourceSecurityGroupId do
          Ref "sgAMIMOTO11AutogenByAWSMPNFS"
        end
      }
    ]
  end
end
